language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.4
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

install:
    - composer install

script:
    - composer validate --strict
    - ./vendor/bin/ecs check src tests
    - ./vendor/bin/phpunit
    - ./vendor/bin/phpstan analyse src tests --level max

after_success:
    - travis_retry php vendor/bin/php-coveralls -v
